<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_views_data_alter().
 */
function month_views_filter_filter_views_data_alter(array &$data) {
  $data['TABLE_NAME']['IDENTIFICATOR'] = [
    'title' => t('Month Filter'),
    'filter' => [
      'title' => t('Month Filter'),
      'help' => t('Month Filter'),
      'field' => 'DATE_RANGE_FIELD_MACHINE_NAME',
      'group' => 'Search',
      'id' => 'FILTER_ID',
    ],
  ];
}